spring:
  application:
    name: peach-monitor
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 8101cc6a-23af-46e3-b704-390d24aa58ab
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        group: PEACH-CLOUD
        namespace: 8101cc6a-23af-46e3-b704-390d24aa58ab
        enabled: true
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}?group=${spring.cloud.nacos.config.group}&namespace=${spring.cloud.nacos.config.namespace}
      - optional:nacos:application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}?group=${spring.cloud.nacos.config.group}&namespace=${spring.cloud.nacos.config.namespace}
